[package]
name = "kind-target-hvm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kind-span = { path = "../kind-span" }
kind-tree = { path = "../kind-tree" }
kind-report = { path = "../kind-report" }
kind-derive = { path = "../kind-derive" }

hvm = { git = "https://github.com/Kindelia/HVM.git" }