[package]
name = "kind-checker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kind-tree = { path = "../kind-tree", version = "0.1.0" }
kind-span = { path = "../kind-span", version = "0.1.0" }
kind-report = { path = "../kind-report", version = "0.1.0" }

hvm = "1.0.0"

fxhash = "0.2.1"
im-rc = "15.1.0"