[package]
name = "kind2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hvm = "0.1.38"
clap = { version = "3.1.8", features = ["derive"] }
