[workspace]
members = [
  "src/kind-cli",
  "src/kind-tree",
  "src/kind-span",
  "src/kind-parser",
  "src/kind-pass",
  "src/kind-report",
  "src/kind-checker",
  "src/kind-driver",
  "src/kind-report",
  "src/kind-target-kdl",
  "src/kind-target-hvm",
  "src/kind-derive",
  # "src/kind-optimization",
  # "src/kind-lint",
  # "src/kind-query",
  # "src/kind-macros",
]