[package]
name = "kind-span"
version = "0.1.1"
edition = "2021"
license = "MIT"
description = "Describes locations for the Kind compiler"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
