[package]
description = "Describes locations for the Kind compiler"
edition = "2021"
license = "MIT"
name = "kind-span"
version = "0.1.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
