[package]
name = "kind-parser"
version = "0.1.1"
edition = "2021"
license = "MIT"
description = "Parser for the kind compiler"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kind-span = { path = "../kind-span", version = "0.1.1" }
kind-tree = { path = "../kind-tree", version = "0.1.1" }
kind-report = { path = "../kind-report", version = "0.1.1" }

fxhash = "0.2.1"