[package]
name = "kind-checker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kind-tree = { path = "../kind-tree" }
kind-span = { path = "../kind-span" }
hvm = "0.1.81"
fxhash = "0.2.1"